---
- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: no

- name: excute the dotfile script
  shell: "cd {{ dotfiles_home }} && bash bootstrap.sh"
  register: existing_dotfile_info
  failed_when: false
  check_mode: no
